name: Redeploy ECR

on:
  workflow_dispatch:  # Allows you to manually trigger this workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Redeploy Backend
      run: |
          aws ecs update-service --cluster program-resource-tf --service program-resource-tf --force-new-deployment > /dev/null 2>&1
          aws ecs update-service --cluster program-resource-tf --service backend-service-5002 --force-new-deployment > /dev/null 2>&1