name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Terraform workspace to destroy'
        required: false
        default: 'default'

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform-ecs

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Plan the destruction (optional)
      - name: Terraform Plan
        run: terraform plan

      # Destroy the resources
      - name: Terraform Destroy
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform destroy -auto-approve
